---
title: "Module 7"
author: "Flockology"
date: "2024-11-22"
output: html_document
---

```{r setup, include=FALSE}
library(rgbif)
library(tidyverse)
library(MuMIn)
library(rnoaa)
library(data.table)
library(ggmap)
library(usmap)
library(magick)#for examples
library(cowplot)#for examples
library(lme4) #for linear mixed effect models
library(car) #for LME anova testing
library(data.table) #for frollmean function (and others)
library(knitr) 
library(dplyr)
library(purrr)
library(kableExtra) 
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.cap= "**Fig. 1.** Occurence of *Corvus corax* in Massachusetts from 2018. Data from eBird counts."}
raven <- occ_data(scientificName = "Corvus corax", stateProvince="Maine", limit=200,year=2018)

#get the state of ME from ggmaps map data
ME<- map_data('state', 'maine')

raven.p <- ggplot(ME, aes(long,lat,group=subregion) )+
  geom_polygon(colour = "gray",fill="gray90")+geom_point(data=raven[[2]],aes(x=decimalLongitude,y=decimalLatitude,size=individualCount),alpha=0.3,inherit.aes = F)+ coord_quickmap()+theme_void()

#and add image to the map with cowplot
raven.p2 <- ggdraw() +
  draw_image("https://www.allaboutbirds.org/guide/assets/photo/63739491-480px.jpg",scale = 0.3,halign=0,valign=1) +
  draw_plot(raven.p)
print(raven.p2)
```
```{r, eval=FALSE,echo=FALSE,warning=FALSE, message=FALSE}
curlopts=list(http_version=2) #solved a connection during mclapply().

species <- c("Coccyzus americanus","Chordeiles minor","Antrostomus vociferus","Contopus virens","Catharus fuscescens")

gbif_par <- expand_grid(species, y) %>% group_by(species,y) %>% group_split() 

gbif_fun <- function(n){
  occ_data(scientificName = gbif_par[[n]]$species,
           year=gbif_par[[n]]$y,
           month=paste0("3",",","6"),
           limit=5000,
           country="US",
           basisOfRecord = "HUMAN_OBSERVATION",
           stateProvince="Massachusetts")[[2]]
}

 system.time(dat_l <-  mclapply(X=1:length(gbif_par),gbif_fun))

dat <- rbindlist(dat.l,fill=T)

#saving data
saveRDS(dat,"massbird.data.RDS")
```

```{r species count vs year,echo=FALSE,warning=FALSE,message=FALSE, fig.cap= "**Fig. 2.** Occurence of five TGM species in Massachusetts from 1990 to 2019."} 
#year by year totals from occ_data()
dat <- readRDS("massbird.data.RDS")

dat%>%
  group_by(year,species)%>%
  summarise(count=sum(individualCount,na.rm = T))%>%
  ggplot(aes(x=year,y=count,col=species))+geom_point()
```
```{r,include=FALSE}
options(noaakey = "jTfIdOHJgvxYtIgGoFKkISyKebxUwMkz")
sts <- c(
  "GHCND:USW00013894", #Mobile, AL 2k away about 10 days away @200 km/day
  "GHCND:USW00013881", #Charlotte, NC 1000 km away about 6 days away @200 km/day
  "GHCND:USW00014739" #Boston
)

bos <- ncdc_stations(stationid = "GHCND:USW00014739")

sta.d <- bind_rows( # Bind the rows
  lapply(sts, function(x) ncdc_stations(stationid = x)$data) # Use lapply to fetch station data
) %>%
  mutate(
    name = str_sub(name, -5, -4), # Simplify the name column, grab just the state
    migr.day = c(10, 5, 0)        # Migration days from arrival in Boston
  ) %>%
  usmap_transform(input_names = c("longitude", "latitude"), 
                  output_names = c("longitude.1", "latitude.1")) # Correctly transform lat/long

```

```{r,echo=FALSE,warning=FALSE,message=FALSE, make mc}
mc<- dat%>%
  group_by(species, year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))%>%
  filter(year>1999)

mc%>%
  ggplot(aes(j.day,prop))+geom_point()+facet_wrap(year~.)

mc.pred <- mc%>%
  group_by(year)%>%
 summarize(
   pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),#predict the logistic curve for each species
   j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(j.day,date)) ## add date back to tibble

mc%>%
  ggplot(aes(j.day,prop))+geom_point(aes=0.3)+geom_line(data=mc.pred,aes(x=j.day,y=pred),col="blue",size=2)+facet_wrap(year~.)

# 25% 
mc.arrive.date <-mc.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

mc.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()
```
```{r}
options(noaakey = "jTfIdOHJgvxYtIgGoFKkISyKebxUwMkz")
sts <- c(
  "GHCND:USW00013894", #Mobile, AL 2k away about 10 days away @200 km/day
  "GHCND:USW00013881", #Charlotte, NC 1000 km away about 6 days away @200 km/day
  "GHCND:USW00014739" #Boston
)

sta.d <- bind_rows( #bind the rows
  lapply(sts,function(x) ncdc_stations(stationid = x)$data ) #use lapply to run through stations
)%>%
  mutate(usmap_transform(.,input_names = c("longitude","latitude"),output_names = c("longitude.1", "latitude.1")))%>% #join transformation of lat/long for projection with usmap
  mutate(name=str_sub(name, -5,-4))%>%#simplify the name column, grab just the state
  mutate(migr.day=c(10,5,0))%>% #so we can look at wind speed 0, 5 or 10 days before arrive in boston
  separate(id,into = c("station.type","id"))%>%#need to cut station type out from station id number
  print()
weather.d <- meteo_pull_monitors(sta.d$id,date_min = "2000-01-01")
head(weather.d)

```
```{r}
library(lubridate)
weather.d <- weather.d%>%
 mutate(year = year(date), date = as.Date(date)) %>%
  group_by(year)%>% #group by year so we can compute julian day
 mutate(j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01"))), #add julian day
  date2=date,
  wdir.rad=(180-abs(wdf2-180))*pi/180, #radians so we can use a trig function to compute wind vector, scale degrees first to 180 scale to 2x pi and subtract from 180 (wind comes out of a direction)
  wvec=cos(wdir.rad)*-1*awnd # we want a negative value for positive value for 2x pi
  )%>% #store day in new column
  dplyr::select(id,year,date2,j.day,tmin,tmax,wvec)%>% #select the rows we need
  left_join(sta.d%>%select(id,name,migr.day))%>% #add the station id info (ie. name)
  mutate(j.day=j.day+migr.day)#make j.day ahead of BOS according to the migration days away so we can join weather along path
```
```{r}
mc.arr.weath <- mc.arrive.date%>%
  left_join(weather.d)%>%
  left_join(mc%>%dplyr::select(year,date,j.day))
head(mc.arr.weath)

weather.wk <-weather.d %>% 
  group_by(year,name) %>% 
  mutate(wk.tmin = frollmean(tmin, n=14,align="right"),
         wk.tmax = frollmean(tmax, n=14,align="right"),
         wk.wvec = frollmean(wvec, n=14,align="right")
         )%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)
mc.arr.weath2 <- mc.arrive.date%>%
  left_join(weather.wk)
head(mc.arr.weath2)
```
```{r}
mc.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),mc.arr.weath,na.action = "na.fail")
Anova(mc.lmer)
mc.lmer2 <- lmer(j.day ~ wk.tmin * wk.tmax * wk.wvec + (1|name), mc.arr.weath2, na.action = "na.fail")
Anova(mc.lmer2) 

mc.arr.aic <- dredge(mc.lmer2,fixed = c("wk.tmin","wk.tmax","wk.wvec"),)

mc.kb <- kable(mc.arr.aic[1:4,],caption = "**Table 4.** Fit values for nested models of the most complicated linear mixed-effect model.")
```
```{r}
kable_styling(mc.kb)
```
```{r}
best.lmer <-  lmer(j.day~wk.tmin+wk.tmax+wk.wvec+(1|name),mc.arr.weath2,na.action = "na.fail")

Anova(best.lmer)
```

```{r, does arrival time vary according to temperature and wind variables along migration route for TGM's migrating to Massachusettes}
mc.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),mc.arr.weath,na.action = "na.fail")
Anova(mc.lmer)
mc.lmer2 <- lmer(j.day ~ wk.tmin * wk.tmax * wk.wvec + (1|name), mc.arr.weath2, na.action = "na.fail")
Anova(mc.lmer2) 
```

